### ISSUE TITLE
Implicit error handling

### ISSUE THREAD

**Issue by dhardy** [dhardy/rand#25]
We currently have these error kinds (#9):

    /// Permanent failure: likely not recoverable without user action.
    Unavailable,
    /// Temporary failure: recommended to retry a few times, but may also be
    /// irrecoverable.
    Transient,
    /// Not ready yet: recommended to try again a little later.
    NotReady,
    /// Uncategorised error
    Other,

`next_u32` etc. and `fill_bytes` cannot report an error except via panic. Instead, these functions should probably:

 - [ ] block if `NotReady`
 - [ ] retry a few times if `Transient`

Additionally,

 - [x] [all functions should implicitly retry on interrupt](https://github.com/dhardy/rand/issues/9#issuecomment-337858764)

---

There is some room for discussion here (especially how to handle `Transient`), but mostly this issue is to track implementation (PRs welcome).

**Comment by dhardy** [comment]
Specifically, see the impl of `Rng` for `ReadRng` and `OsRng` which both currently unwrap errors.

**Comment by burdges** [comment]
I think our lacking an associated error type will hamper error propagation in many situations where you'd actually care about the error.  I asked a summary so far question to help document this and other compromises https://github.com/dhardy/rand/issues/29 but I'm kinda guessing there.

**Comment by dhardy** [comment]
@burdges (1) this point is about handling specific errors, not about propagating errors (#8 and #10 are more on topic for that), and (2) if we had an associated error type then we can have no generic handling (e.g. `from_rng` must either use `fill_bytes` for implicit error handling but panic, or `try_fill_bytes` to allow error propagation but do no implicit handling), so associated types *make the situation worse*.

**Comment by burdges** [comment]
It's worth glancing at the boats' new [failure crate](https://github.com/withoutboats/failure) ([via](https://www.reddit.com/r/rust/comments/7b88qp/failure_a_new_error_management_story/?st=j9r7c4u1&sh=a60720c5)), but it [fails `no_std` projects immediately](https://boats.gitlab.io/failure/doc/src/failure/error.rs.html#21-23) so not ideal here.

**Comment by dhardy** [comment]
@burdges you're off topic in this issue for the second time. See also [this comment](https://www.reddit.com/r/rust/comments/7b88qp/failure_a_new_error_management_story/dpgyyvk/); `failure` doesn't help much with this problem.

**Comment by dhardy** [comment]
#35 implements this for reseeding

**Comment by dhardy** [comment]
Note: interrupt handling is only required for `std::io::Read`; both implementations use `read_exact` which already retries on interrupt.

**Comment by dhardy** [comment]
It seems any implicit handling is being done locally (context-dependent), so no need for this issue.
