### ISSUE TITLE
Rename `try_fill` or `fill_bytes`?

### ISSUE THREAD

**Issue by dhardy** [dhardy/rand#27]
I'm not going to break out regexxer yet because I'm not convinced either way yet, but we should probably [resolve this](https://github.com/dhardy/rand/issues/8#issuecomment-338633414).

**Comment by pitdicker** [comment]
An other thought: for `try_fill` it may make sense to return the number of filled bytes. In case of an error, maybe there is still part of the result ready.

``` rust
fn try_fill(&mut self, dest: &mut [u8]) -> Result<usize, Error>;
```

If we go this route, `fill_bytes` should return the number of filled bytes too. If we were to make this change, it seems ok to me to also change the name to `fill`.

``` rust
fn fill(&mut self, dest: &mut [u8]) -> usize;
```

**Comment by newpavlov** [comment]
I personally prefer `fill` more, as bytes part should be clear from the type signature. Also `try_fill_bytes` feels a bit clunky. But I can live with the old name as well.

**Comment by dhardy** [comment]
But @pitdicker `try_fill` should fill the buffer *unless* it fails, so it only makes sense to return a `usize` on error — unless this becomes like typical read functions which may succeed with less data than requested, but this significantly complicates usability.

**Comment by pitdicker** [comment]
Hm yes I messed up. If you return `Result<usize, Error>` it will give either a `usize` or an `Error`, not both. Then there is no argument in that for renaming.

There is no other simple way to say a slice is only partially filled, is there?

I don't have a preference for `fill` vs `try_fill`. Well, I like `fill` more, but do not al that much given the breakage.

It is not completely clear to me how much breakage we have until now. Is it only a little, or so much one more change does not really make it worse?

**Comment by dhardy** [comment]
I don't know; I guess there are a fair few users of `rand` by now, but no idea how many use `fill_bytes`.

**Comment by dhardy** [comment]
We merged `try_fill_bytes`: https://github.com/rust-lang-nursery/rand/pull/225
