### ISSUE TITLE
Move external RNGs?

### ISSUE THREAD

**Issue by dhardy** [dhardy/rand#61]
As [noted here](https://github.com/dhardy/rand/issues/15#issuecomment-346841971), the external RNGs `OsRng` and `JitterRng` could easily be moved to another crate and may be of use to users not needing other parts of `rand` (especially crypto libraries).

Three options:

*   keep in `rand`
*   move to a new crate
*   move to `rand-core`

The last one may not be ideal; part of the rationale for `rand-core` was to make it a small, easily reviewable API crate (a goal it already does poorly on).

@briansmith @jmst @bhickey @nagisa @joshlf, any opinion on this?

**Comment by arthurprs** [comment]
I think it's ok to keep it into `rand`, if it ever becomes a problem it can be moved out (and be re-exported from rand).
