### ISSUE TITLE
Move `utils::FloatConversions` to `rand_core`

### ISSUE THREAD

**Issue by pitdicker** [dhardy/rand#70]
It seems to me conversions to floats are fundamental enough to be part of `rand_core`. While you probably want some sort of distribution or range when _using_ floats, these conversion functions are building blocks to provide a distribution or range.

**Comment by dhardy** [comment]
I don't see much point moving FP stuff into rand-core; it's only really aimed at cryptographic users and RNG implementations (and we already decided to remove `next_f32` / `next_f64` from `Rng`). Any disagreement or shall I close this?

**Comment by pitdicker** [comment]
Ok, restricting `rand-core` to only the minimum needed for RNG implementations seems like a good idea.
