### ISSUE TITLE
Ascii char generation

### ISSUE THREAD

**Issue by dhardy** [dhardy/rand#73]
Consider renaming `AsciiWordChar` to `AlphanumericChar` and adding `AsciiPrintableChar` or similar.

**Comment by pitdicker** [comment]
Thinking about it some more, I don't really see much use for these functions outside of testing. I would say let's not add `AsciiPrintableChar` until there people are asking for it.

**Comment by pitdicker** [comment]
I think this can be closed after https://github.com/dhardy/rand/pull/75?
